### ISSUE TITLE
ImportError: cannot import name 'JSONWebSignatureSerializer' from 'itsdangerous'

### ISSUE THREAD

**Issue by khteh** [puiterwijk/flask-oidc#147]
`Python 3.10.4`
`pipenv, version 2022.5.2`
Exception happens on the following import line:
```
from flask_oidc import OpenIDConnect
```

**Comment by Mikaciu** [comment]
Hello, 
This class has been removed in `itsdangerous` 2.1.0 : https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

It was mentioned in https://github.com/puiterwijk/flask-oidc/issues/3 ...

In your Pipfile, could you please add `itsdangerous = "<2.1"` ?

**Comment by khteh** [comment]
How long can you stay in this deprecated functionality? Instead of going backward, it should be updated to use proper library as described here:

https://itsdangerous.palletsprojects.com/en/2.1.x/changes/
https://docs.authlib.org/en/latest/jose/jws.html

**Comment by Mikaciu** [comment]
I honestly don't know, I had the same issue several days ago and thought it would be helpful to share ;)

**Comment by ecederstrand** [comment]
Apparently fixed in https://github.com/puiterwijk/flask-oidc/pull/144

**Comment by gcalmettes** [comment]
confirming that installing #144 fixes it.

**Comment by khteh** [comment]
Fixed? Install? What do you mean and how? https://github.com/puiterwijk/flask-oidc/pull/144 is not even merged yet!?

**Comment by gcalmettes** [comment]
@khteh you can install the changes introduced by #144 by specifying directly the MR or the commit you want in your `pip install` command.

e.g.: `pip install git+https://github.com/puiterwijk/flask-oidc.git@b10e6bf881a3fe0c3972e4093648f2b77f32a97c`

On our end, we are using a custom security manager for Airflow to connect using OIDC, which relies on `flask-oidc` underneath (https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-openid). Because the dependency on `itsdangerous` is not pinned, the latest build broke the oidc workflow to connect to Airflow, but adding the latest commit of  #144 as dependency in our docker build (command above) fixed it.

**Comment by khteh** [comment]
What stops you from merging and releasing the fix as a new version?

**Comment by gcalmettes** [comment]
@khteh well, one would need to have the proper rights on the repo for that, so this decision relies on @puiterwijk’s approval of the PR.
In the meantime targeting the code of the PR for the install  is a workaround.

**Comment by khteh** [comment]
Ok. Thanks. BTW, what's `MR`?

**Comment by gcalmettes** [comment]
Sorry, I mixed the Gitlab’s way of defining things. MR = Merge request (which is Gitlab’s denomination for Pull Request).

**Comment by khteh** [comment]
I failed to install it using `pipenv`:
```
$ pipenv install git+https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head#egg=flask-oidc
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Installing git+https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head#egg=flask-oidc...
Error:  An error occurred while installing git+https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head#egg=flask-oidc!
Error text: Collecting flask-oidc
  Cloning https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head to /tmp/pip-install-2sdrfu86/flask-oidc_f913d0b02d084fdea2ae53e1b814d2d2

  Running command git clone --filter=blob:none --quiet https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head /tmp/pip-install-2sdrfu86/flask-oidc_f913d0b02d084fdea2ae53e1b814d2d2
  remote: Not Found
  fatal: repository 'https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head /tmp/pip-install-2sdrfu86/flask-oidc_f913d0b02d084fdea2ae53e1b814d2d2 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/puiterwijk/flask-oidc.gitrefs/pull/144/head /tmp/pip-install-2sdrfu86/flask-oidc_f913d0b02d084fdea2ae53e1b814d2d2 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

✘ Installation Failed 
```

**Comment by MrMarshall** [comment]
@puiterwijk could this PR please be merged and released?

**Comment by ecederstrand** [comment]
Yes. See https://github.com/puiterwijk/flask-oidc/issues/147#issuecomment-1207160732

**Comment by Nixellion** [comment]
So it's 2023, 4 months later, is this still the issue and is it not yet updated?

**Comment by macmule** [comment]
Came here hoping for a fix too.

**Comment by frozenpandaman** [comment]
Still waiting on a fix…
